BelajarMvcWeb/Areas/Admin/Controllers/CompanyController.cs
using BelajarMvcWeb.DataAccess.Repository.IRepository;
using BelajarMvcWeb.Models;
using BelajarMvcWeb.Models.ViewModels;
using BelajarMvcWeb.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BelajarMvcWeb.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = $"{SD.Role_Admin},{SD.Role_Employee}")]

    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? Id = 0)
        {
            Company company = new();
            if (Id != 0)
            {
               company = _unitOfWork.Company.GetFirstOrDefault(u => u.Id == Id);
            }
            //ViewBag.CategoryList = categoryList;
            //ViewData["CoverTypeList"] = coverTypeList;
            return View(company);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Company obj)
        {
            if (!ModelState.IsValid) return View(obj); //if there's errors, ModelState will be populated
            if (obj.Id == 0)
            {
                _unitOfWork.Company.Add(obj);
                TempData["success"] = "Product Data added successfully";
            }
            else
            {
                _unitOfWork.Company.Update(obj);
                TempData["success"] = "Product Data edited successfully";
            }
            _unitOfWork.Save();
            return RedirectToAction("Index"); //second param is controller/route name
        }

        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0) return NotFound();
            var company = _unitOfWork.Company.GetFirstOrDefault(x => x.Id == Id); // there is single/singleordefault, first/firstordefault
            if (company == null) return NotFound();
            _unitOfWork.Company.Remove(company);
            _unitOfWork.Save();
            TempData["success"] = "Data deleted Successfully";
            return RedirectToAction("Index");
        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var companyLists = _unitOfWork.Company.GetAll();
            return Json(new
            {
                data = companyLists,
            });
        }

        [HttpDelete]
        public IActionResult Delete(int Id)
        {
            var company = _unitOfWork.Company.GetFirstOrDefault(x => x.Id == Id);
            if (company is null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _unitOfWork.Company.Remove(company);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete Success" });
        }
        #endregion
    }
}

BelajarMvcWeb/Areas/Admin/Controllers/CoverTypeController.cs
using BelajarMvcWeb.DataAccess.Repository.IRepository;
using BelajarMvcWeb.Models;
using BelajarMvcWeb.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BelajarMvcWeb.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = $"{SD.Role_Admin},{SD.Role_Employee}")]
    public class CoverTypeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CoverTypeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<CoverType> objCoverTypeList = _unitOfWork.CoverType.GetAll();
            return View(objCoverTypeList);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType cover)
        {
            var coverName = _unitOfWork.CoverType.GetFirstOrDefault(x => x.Name == cover.Name);
            if (coverName != null) ModelState.AddModelError("Name", "Cover Name already exists");
            if (!ModelState.IsValid) return View(cover); //if there's errors, ModelState will be populated
            _unitOfWork.CoverType.Add(cover);
            _unitOfWork.Save();
            TempData["success"] = "Data created Successfully";
            return RedirectToAction("Index"); //second param is controller/route name
        }

        public IActionResult Edit(int? Id)
        {
            if (Id == null || Id == 0) return NotFound();
            var cover = _unitOfWork.CoverType.GetFirstOrDefault(x => x.Id == Id); // there is single/singleordefault, first/firstordefault
            if (cover == null) return NotFound();
            return View(cover);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType cover)
        {
            var cov = _unitOfWork.CoverType.GetFirstOrDefault(x => x.Id == cover.Id);
            if (cov == null) return NotFound();
            if (!ModelState.IsValid) return View(cover); //if there's errors, ModelState will be populated
            _unitOfWork.CoverType.Update(cover);
            _unitOfWork.Save();
            TempData["success"] = "Data edited Successfully";
            return RedirectToAction("Index"); //second param is controller/route name
        }

        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0) return NotFound();
            var cover = _unitOfWork.CoverType.GetFirstOrDefault(x => x.Id == Id); // there is single/singleordefault, first/firstordefault
            if (cover == null) return NotFound();
            _unitOfWork.CoverType.Remove(cover);
            _unitOfWork.Save();
            TempData["success"] = "Data deleted Successfully";
            return RedirectToAction("Index");
        }
    }
}

BelajarMvcWeb/Areas/Admin/Controllers/ProductController.cs
using BelajarMvcWeb.DataAccess.Repository.IRepository;
using BelajarMvcWeb.Models;
using BelajarMvcWeb.Models.ViewModels;
using BelajarMvcWeb.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BelajarMvcWeb.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = $"{SD.Role_Admin},{SD.Role_Employee}")]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        private readonly IWebHostEnvironment _hostEnvironment;
        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? Id = 0)
        {
            ProductVM productVM = new()
            {
                Product = new(),
                CategoryList = _unitOfWork.Category.GetAll().Select(
                    u => new SelectListItem
                    {
                        Text = u.Name,
                        Value = u.Id.ToString(),
                    }
                ),
                CoverTypeList = _unitOfWork.CoverType.GetAll().Select(
                    u => new SelectListItem
                    {
                        Text = u.Name,
                        Value = u.Id.ToString(),
                    }
                ),
            };
            if (Id != 0)
            {
               productVM.Product = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == Id);
            }
            //ViewBag.CategoryList = categoryList;
            //ViewData["CoverTypeList"] = coverTypeList;
            return View(productVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM obj, IFormFile? file)
        {
            if (!ModelState.IsValid) return View(obj); //if there's errors, ModelState will be populated
            string wwwRootPath = _hostEnvironment.WebRootPath;
            if(file is not null)
            {
                string fileName = Guid.NewGuid().ToString();
                var uploads = Path.Combine(wwwRootPath, @"images\product");
                var extension = Path.GetExtension(file.FileName);

                if(obj.Product.ImageUrl != null)
                {
                    var oldImagePath = Path.Combine(wwwRootPath, obj.Product.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }

                using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                {
                    file.CopyTo(fileStreams);
                }
                obj.Product.ImageUrl = @$"\images\product\{fileName+extension}";
            }
            if (obj.Product.Id == 0)
            {
                _unitOfWork.Product.Add(obj.Product);
                TempData["success"] = "Product Data added successfully";
            }
            else
            {
                _unitOfWork.Product.Update(obj.Product);
                TempData["success"] = "Product Data edited successfully";
            }
            _unitOfWork.Save();
            return RedirectToAction("Index"); //second param is controller/route name
        }

        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0) return NotFound();
            var product = _unitOfWork.Product.GetFirstOrDefault(x => x.Id == Id); // there is single/singleordefault, first/firstordefault
            if (product == null) return NotFound();
            _unitOfWork.Product.Remove(product);
            _unitOfWork.Save();
            TempData["success"] = "Data deleted Successfully";
            return RedirectToAction("Index");
        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var productLists = _unitOfWork.Product.GetAll(includeProperties: "Category");
            return Json(new
            {
                data = productLists,
            });
        }

        [HttpDelete]
        public IActionResult Delete(int Id)
        {
            var product = _unitOfWork.Product.GetFirstOrDefault(x => x.Id == Id);
            string wwwRootPath = _hostEnvironment.WebRootPath;
            if (product is null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
                var oldImagePath = Path.Combine(wwwRootPath, product.ImageUrl.TrimStart('\\'));
                if (System.IO.File.Exists(oldImagePath))
                {
                    System.IO.File.Delete(oldImagePath);
                } 
            _unitOfWork.Product.Remove(product);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete Success" });
        }
        #endregion
    }
}

BelajarMvcWeb/ViewComponents/ShoppingCartViewComponent.cs
using BelajarMvcWeb.DataAccess.Repository.IRepository;
using BelajarMvcWeb.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BelajarMvcWeb.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;

        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                if (HttpContext.Session.GetInt32(SD.SessionCart) != null)
                {
                    return View(HttpContext.Session.GetInt32(SD.SessionCart));
                }
                else
                {
                    var count = _unitOfWork.ShoppingCart.GetAll(s => s.ApplicationUserId == claim.Value).Count();
                    HttpContext.Session.SetInt32(SD.SessionCart, count);
                    return View(HttpContext.Session.GetInt32(SD.SessionCart));
                }
            }
            HttpContext.Session.Clear();
            return View(0);
        }
    }
}

BelajarMvcWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using BelajarMvcWeb.Utility
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BelajarMvcWeb</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BelajarMvcWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">BelajarMVCWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">
                                Home
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Employee))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Contents Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">CoverType</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    <div class="dropdown-divider"></div>
                                </div>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Cart" asp-area="Customer" asp-action="Index">
                                Cart&nbsp
                                @await Component.InvokeAsync("ShoppingCart")
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">Order</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary">
        <div class="container">
            &copy; 2022 - BelajarMvcWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-muted">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/9szd1hg5iz42z5u9ztjbf7glnhyhg3pbqooewhkek3llsfik/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @*render section make all scripts above will not included in all pages, for better performance*@
</body>
</html>

BelajarMvcWeb/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
    toastr.success('@TempData["success"]', "Success")
    </script>
}

@if(TempData["failed"] != null)
{
     <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
     <script type="text/javascript">
    toastr.error('@TempData["failed"]', "Failed")
    </script>
}